# App metadata; see https://appfair.net/#App.yml

# Fastlane metadata keys:
# https://docs.fastlane.tools/actions/deliver/#non-localized-metadata
# Note: localized keys for app title, subtitle, description, etc.
# should defined in localized resources instead of here:
# Sources/App/Resources/*.lproj/Localizable.strings
app:
  primary_category: "GAMES"
  secondary_category: "ENTERTAINMENT"
  subtitle: "A game of whimsey!"
  promotional_text: "The Great Cloud Cuckoo comes to the App Store!"
  description: |
    A simple and delightful game. Tap the Cuckoo circle to maximize your simulated profits.
    As you progress, the number of dots will grow, making the Cuckoo harder to spot. Don't give up!
    This game is a free and open-source app developed under the Affero General Public License and distributed by the App Fair Project. Learn more at appfair.org.

  keywords: "cloud,cuckoo,appfair,game,flappy,bird"
  localizations: # keys like "fr-FR" can contain localized description, name, etc.
    fr-FR:
      name: "Le Cuckoo Cloud"
      subtitle: "Un jeu amusant!"
    de-DE:
      name: "Die Cuckoo Cloud"
      release_notes: "glaenzend und neu"

markets:
  testflight: "1639746748"
  testflighturl: "https://testflight.apple.com/join/IrPLgy5Q"
  appstore: "1639746748"      # the assigned App Store id
  #playstore: "123456543210"   # the assigned Play Store id

# Pages / Jekyll configuration::
remote_theme: "appfair/fairapp-theme"

# the app icon is generated from a simple SVG path and a tint color
icon:
  # gradient tint color (symbolic name or "#RRGGBB")
  # tint: "red"
  # SVG path to place in the center of the icon
  # path: "M0 200 v-200 h200 a100,100 90 0,1 0,200 a100,100 90 0,1 -200,0 z"


